# Generated by Django 4.2.19 on 2025-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaytransaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
